backend: git-gateway
media_folder: "static/img"
media_library:
  name: images

collections:
  - name: "rooms"
    label: "rooms"
    description: "Rooms information."
    folder: "src/pages/index"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
